<?php

namespace Plugin\SnsLogin\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SnsLoginConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnsLoginConfigRepository extends EntityRepository
{
}
